in this commit i saved the progress of the game
pedrosv20/MacroChallenge pull request #50
Opened 2020-09-09 13:13 UTC by lucasronnau

in this commit i saved the progress of the game, add the checkPoints in scene, and save position, levelState, if get Wrench and if monster dead

2020-09-09 13:37 UTC, pedrosv20 requested changes

2020-09-09 13:37 UTC, pedrosv20 commented on MacroChallenge/MacroChallenge/Controller/LevelController.swift
> +    let instance = Model.instance
```suggestion
    typealias instance = Model.instance
```

2020-09-09 13:37 UTC, pedrosv20 commented on MacroChallenge/MacroChallenge/Model/Model.swift
> +    let name: String
aqui n vai precisar saber a vida do monstro e os pontos de ataque?

2020-09-10 14:04 UTC, mateusnunesnunes requested changes

2020-09-11 12:03 UTC, mateusnunesnunes approved these changes

2020-09-11 12:13 UTC, pedrosv20 approved these changes

2020-09-11 12:13 UTC, merged